# Generated by Django 5.1.3 on 2025-03-01 19:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='feedback',
            new_name='cover_letter',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Internship',
            new_name='internship',
        ),
        migrations.RemoveField(
            model_name='application',
            name='company',
        ),
        migrations.RemoveField(
            model_name='application',
            name='date_applied',
        ),
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
